
import "../styles/globals.css";


import Navigation from "@/components/Navigation";
import Sidebar from "@/components/Sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav style={{marginTop:"3rem"}}>
        
      <Navigation />
     <Sidebar /> 

 </nav>
        </header>
        <main>
        {children} 
        </main>
        
      </body>
    </html>
  );
}
